name: pod
description: >
  A dependency injection and state management library,
  fast, simple and composable inspired by Riverpod and JÅtai.
version: 0.18.0
repository: https://github.com/Eronildo/pod/tree/master/packages/pod
homepage: https://github.com/Eronildo/pod
topics: [riverpod, pod, atom, dependency-injection, state-management]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.3.0
